### PR TITLE
Use bytes on pickle SpatialPooler and TemporalMemory

### PR DESCRIPTION
**Pull request by Lupino**
Fixed UnicodeDecodeError,   when pickle SpatialPooler or TemporalMemory

#160

### CODE REVIEW

**Comment by ctrl-z-9000-times** [comment]
Hi Lupino,

I think I know why you code does not work.  It looks like a problem with pybind11 and python2.  I found this thread discussing it: https://github.com/pybind/pybind11/issues/271

Try replacing `import pickle` with:
```py
try:
    import cPickle as pickle # For python 2
except ImportError:
    import pickle # For python 3
```

**Comment by Lupino** [comment]
> Hi Lupino,
> 
> I think I know why you code does not work. It looks like a problem with pybind11 and python2. I found this thread discussing it: [pybind/pybind11#271](https://github.com/pybind/pybind11/issues/271)
> 
> Try replacing `import pickle` with:
> 
> ```python
> try:
>     import cPickle as pickle # For python 2
> except ImportError:
>     import pickle # For python 3
> ```

I changed but also failed

**Comment by Lupino** [comment]
https://github.com/htm-community/nupic.cpp/blob/master/bindings/py/tests/nupic_random_test.py#L76 

I found pickle is mark failed on this file.

**Comment by ctrl-z-9000-times** [comment]
I think that the next best thing would be to detect which version of python is running and skip the unit tests if it's python 2.  Then at least we can have this working and tested for python3.

The pytest docs have some examples of how to do this:
https://docs.pytest.org/en/latest/skipping.html?highlight=skipping#id1

**Comment by breznak** [comment]
This ended up a really nice PR! Thank you @Lupino :+1:

**Pull request merged**
