### PR TITLE
completed the .py rest example

### PR DESCRIPTION
**Pull request by dkeeney**
See issue #785 

This completes the REST example using Python. 
My Python skills are not very strong so feel free to 'clean up' the code if you need to.

### CODE REVIEW

**Comment by dkeeney** [comment]
The performance test is failing.  This PR could not have increased the performance time so I am running this again to see if this is consistent.

**Comment by dkeeney** [comment]
Ok, I guess the performance test is passing again.
Once this is in we should do a new release.

**Comment by dkeeney** [comment]
This PR is waiting for a review.

**Comment by breznak** [comment]
This is now a PRO functionality! :clap: Thanks @dkeeney

**Comment by dkeeney** [comment]
Thank you.

**Pull request merged**
