### PR TITLE
Connections try float16 for optimization (float is faster) 

### LINKED ISSUE #360: Connections: optimize data types' cache utilization: half, float16
After typedefs from PR #331 are merged to Connections: 

- [ ] experiment with smaller data-types for better CPU cache utilization
  - [ ] other thing is auto-vectorization/SIMD which uses int32,float
  - [ ] try half_t float16 for Permanence
- [ ] add ConnectionsPerformance test using valgrind  CacheGrind to actually measure cache use
  - [ ] for hotgym (SP, TM)
  - [ ] MNIST (SP, CP)

Ref: #161

### PR DESCRIPTION
**Pull request by breznak**
WIP on using float 16 type for Permanence. 

Ref https://github.com/etaler/Etaler/issues/12 

- compiles
- problem is I cannot find any doc on Eigen::half
- Cereal has problem with it
- compiles OK if I use Permenence=half only in Connections.cpp, .hpp stays Real32.
  - suprisingly mem footprint is not reduced at all (do I just convert around, but still store in Real32?)
  - runtime was tiny faster

- [ ] I'd like to find a better documented float16 library for CPU 
- [ ] compare floating-point math with discrete, where we simulate Permanence as `unsugned char`

Fixes #360

### CODE REVIEW

**Comment by ctrl-z-9000-times** [comment]
Another idea for optimizing Permanences is to use 16 bit integers.
Scale all permanence values from `[0.0 - 1.0]` to `[0 - 2^16)`

**Comment by breznak** [comment]
> Another idea for optimizing Permanences is to use 16 bit integers.

yes, this would likely be better approach for us. I want to give a shot to the float way, as that would be more natural, but if results are not worth, let's try with `Permanence = unsigned char`

**Comment by marty1885** [comment]
@breznak Did you have any progress on the topic. I have just tried FP16 on Aarch64 processors. Well.. it's underwhelming. The performance is exactly the same (besides noise-level differences). Hopefully I'm doing something very wrong.

**Comment by breznak** [comment]
> Do you have any progress on the topic? 

unfortunately no. I've just briefly tested with the `float16` (Eigen::half) and saw no reduction in mem/cpu usage. My conclusion is that for now (until Intel CPUs come with `bfloat` support in HW) all "float16" on x86 is only emulated and brings no speedups (I still don't know why atleast the mem didn't see a reduction). 

We do have now an ARM64 build in CI but again it's only emulated, not on real HW. ( I can retry on there too, if atleast the memory footprint improves). 

> optimizing Permanences is to use 16 bit integers.
Scale all permanence values from [0.0 - 1.0] to [0 - 2^16)

untried but "should work well on x86" idea is still to replace floats with emulation through uint16. Have you gone that way?

**Comment by marty1885** [comment]
> untried but "should work well on x86" idea is still to replace floats with emulation through uint16. Have you gone that way?

No, but I doubt it will be faster on modern x86 processors. AMD have a separate pipeline for floating point so you get better throughput by mixing floating point and other control flows. Intel can schedule up-to 4 FP operations along side with other instructions. I don't think we are doing that much FP operations to saturate that.

I just finished testing `float16` on ARM64. And see barely no performance improvements. Hopefully it's some bad code.

**Comment by breznak** [comment]
> I just finished testing float16 on ARM64. And see barely no performance improvements. Hopefully it's some bad code. 

even for mem footprint? 
Would a (native?) float16 be applicable for ARM for us here easily? We could make an IFDEF in `Types.hpp` where `Real (=float)` is defined.

**Comment by marty1885** [comment]
> even for mem footprint?
The memory footprint is better comparing to `float32`. But no difference on computing time.

> Would a (native?) float16 be applicable for ARM for us here easily? 
That's my problem. I tried to switch to native FP16 on ARM64 (for Etaler). But results shows no difference in computation time compared to float32.

**Comment by breznak** [comment]
> The memory footprint is better comparing to float32. But no difference on computing time. 

by 2x? Even that would be a huge success wrt. the ability to run large(r) networks, I guess esp on GPUs where the RAM is scarce. 

> That's my problem. I tried to switch to native FP16 on ARM64 (for Etaler). 

Could you please point me to the code where you define this? I guess it'll be a quite simple, device-specific define (?). 

I'd like to try this on our ARM builds. Wonder if any of the benefits mem/cpu would be seen on the emulated machine. And I'll try to buy a RPi4 to play with this on a real HW. 

Once ironed out (in both hw, compilers/c++, and our code), I still expect float16 to be nice improvement. 

> [about idea of uint16 instead of float32, as "float16"]  No, but I doubt it will be faster on modern x86 processors. AMD have a separate pipeline for floating point so you get better throughput by mixing floating point and other control flows. Intel can schedule up-to 4 FP operations along side with other instructions. I don't think we are doing that much FP operations to saturate that.

thanks, this is a valuable explanation! What I expected to be the gain is that the cache fits twice the number of data.

**Comment by marty1885** [comment]
> Could you please point me to the code where you define this? I guess it'll be a quite simple, device-specific define (?).

Here, it's not in the main library but in my FP16 abstraction lib. https://github.com/marty1885/half_precision/blob/8b91e26e16951aad221c8c5ac706f86367524ced/half.hpp#L31

And some template dispatch code is used to generate code for both float32 and float16
https://github.com/marty1885/Etaler/blob/a10243705114fe65e51a734140d36bbb5ea2fea8/Etaler/Backends/CPUBackend.cpp#L321

**Comment by breznak** [comment]
@dkeeney when you have time, I'd like a review on this. 
So far it's only proper casts (for constants etc) to `Permanence` which we treat as "floating point number on [0.0, 1.0]". 

This PR does not use any `float16/half` type for optimization, but makes it easy to do experiments with it. (I tried and results were worse on a CPU than with float32, I may retry). 

So this is code cleanup/enablement for future experimentations.

**Comment by breznak** [comment]
This is an old PR, but weird, some tests are off... 

```
[ RUN      ] ConnectionsTest.testSynapseCompetition
/home/mmm/devel/HTM/htm-community/nupic.cpp/src/test/unit/algorithms/ConnectionsTest.cpp:609: Failure
Expected: (segData.numConnected) <= (test.max), actual: 100 vs 99
/home/mmm/devel/HTM/htm-community/nupic.cpp/src/test/unit/algorithms/ConnectionsTest.cpp:609: Failure
Expected: (segData.numConnected) <= (test.max), actual: 77 vs 30
/home/mmm/devel/HTM/htm-community/nupic.cpp/src/test/unit/algorithms/ConnectionsTest.cpp:609: Failure
Expected: (segData.numConnected) <= (test.max), actual: 88 vs 33
[  FAILED  ] ConnectionsTest.testSynapseCompetition (1 ms)
```

**Review by dkeeney — APPROVED** [review]
Looks good.

**Pull request merged**
