### PR TITLE
Travis fix regex pattern

### PR DESCRIPTION
**Pull request by breznak**
for includes on v1.2.3

### CODE REVIEW

**Comment by dkeeney** [comment]
Are you doing a build of everything as part of the merge?
I thought we would just build the binary release package during the previous PR push and cache it somewhere in the CI and where it is available when the merge occurs.

**Comment by breznak** [comment]
> build of everything as part of the merge?
I thought we would just build the binary release package during the previous PR push and cache it somewhere in the CI and where it is available when the merge occurs

I haven't figured caching yet, so for now: Yes, a tag (in format `vX.Y.Z`) on `master` triggers a new build that is later deployed. (I think it has been done the same way for numenta). 

The idea is that we'd run the semantic releases manualy, so not that frequently (not on each PR), say weekly. 

What I resolved was the duplicit `travis/pr`, `travis/push` builds -> needs the exclude only for master (and then allow the tags)

**Comment by breznak** [comment]
Sorry I havent consulted the PRs, but this can be evaluated only once merged to master, so I needed to trial-err the process.

**Comment by dkeeney** [comment]
>  I havent consulted the PRs,

Not a problem.  I can see that you hare having to do lots of merges in order to figure this out.

**Comment by dkeeney** [comment]
I will hold off on working on the automatic version increment using GitVersion.  I will wait until the work you are doing settles down.

But I don't think that it requires anything being ran at merge time.  At PR push, before the PR build,  it figures out what the version would be if it were merged so that the PR build contains the 'proposed' version number.

**Comment by breznak** [comment]
> I will hold off on working on the automatic version increment using GitVersion.

the thing is if we need that now? 
How it'd work now:
- we develop PRs as normally
- once we decide (significant new feature, or a long time, ..) we manually create a release
  - that means just pushing a tag `git tag v2.0.1 && git push --tags origin`
  - that (now almost) creates a Release for the tag
  - the version numbers are on us to decide
- if we wanted to change that to make a release for each successful PR (maybe not, too noisy?) than that's easy to do too 

What do you think of this workflow?

**Comment by dkeeney** [comment]
I still like bumping the version on each PR but yes it might be rather noisy.  Bumping the Major or Minor numbers should definitely be manual using tags.   However, do what you think best and we can change it later if we need to.

**Pull request merged**
