### PR TITLE
New Feature: phases can be specified with addRegion() and run().

### PR DESCRIPTION
**Pull request by dkeeney**
This adds the ability to specify a set of regions into which a region can be placed.  It also adds the ability to specify a phase or subset of phases to execute with the run() command.

1) Added an optional argument to the addRegion( ) function to specify a set of phases to assign the new region to.  This feature is also implemented in the configuration string used by the Network::configure() function.

2) All regions added without a phase specification are added to phase 0.  Any number of regions can be added to a phase.  A region may be 

3) In the run() function, regions are executed in the order that they are assigned to a phase (which is normally when a region is created).  setEnableMinPhase() and setEnableMaxPhase() can be used to bracket the phases to be executed rather than executing all phases.  The run() function can optionally specify a phase or set of phases to be executed, so they don't need to be consecutive.

### CODE REVIEW

**Comment by dkeeney** [comment]
Work in Progress - just wanted to get this out there so it can be discussed.
This PR completes items in PR #955 

Yet to be implemented... 

- Python bindings: Need to add the phase arguments to addRegion() and run().
- Documentation: need to update the function descriptions
- Fix problem with loops
- Fix problem with dimension propagation.

**Comment by dkeeney** [comment]
The dimension propagation bug I think I can fix...just need to identify where it got lost.

The loop problem will take some more design.
The problem is that when there is a loop and you want the output to loop around and back into the input of the region at the top of the loop. 

For example: Lets say you want to execute regions in this order:     A B C D C D C D E
This can be built with a phase1 ontaining A and B, phase2 has C and D, and phase 3 has E
So, C and D form a loop with a link going from D back to C.   We execute phase1 (A and B) Then we execute phase 2 (C and D) three times, then phase 3 (E). In this scenario,  region C will have two links into it.  The first from an initializing region B and the second from D.

This could be implemented with C having two inputs and C would know to get its first input from the first input with the link from B and all subsequent iterations, get input from the second input with the link from D.  But the region needs to "know" about the loop. Not very usable.

Another way is to use only one input on C with both input going to it.  But by default that would cause a FanIn case where the input would have double the width and each link would provide data for half of the width.  Not quite what we want either.

I can provide a link "mode" where both links would overwrite the buffer so the first input from B would populate the input buffer the first time and the link from D would overwrite the buffer for subsequent iterations.  The problem with this approach is that just before a region executes it gathers its inputs from all connected links...not knowing which link was last to output something.

So, maybe we have to put in a flag somehow to indicate which link to use when populating the input  the overwrite mode is set. I will look at that.

**Comment by dkeeney** [comment]
Another solution is to change the engine a little such that data gets pushed across the links **after** a region executes rather than pulled across the links just **before** a region executes.  This has the advantage that we would not need the special setInputData() facility that I setup some time ago.  Inputs could be written directly to the input buffer by an application.  It would seem more natural.

**Comment by fcr** [comment]
If it helps, in my use case from #955 I did not need to loop the output from D back to C. In my case, C had some internal state that it shared with D. When the looping of C and D finished the result from D continued to E. 
I could have wrapped C and D in an enclosing region which looped them internally but using phases is much more expressive and elegant.
BTW because i liked your solution so much, I made a quick and dirty change to my htm.core copy by simply adding a runPhase method
```
  /**
   * Run the network for the given number of iterations of compute for the
   * Region with phase.
   *
   * For each iteration, Region.compute() is called.
   *
   * @param n Number of iterations
   * @param phase The phase to run
   */
  void runPhase(int n, int phase);
```
which is a modified copy of `run()`. This made it easy to add a Python binding.
This worked very well for my particular use case.

**Comment by dkeeney** [comment]
Thank you @fcr 
I would have had something to check in by now but my wife's computer crashed.  Lost the hard drive. So she gets the priority on my time :)
I expect to be able to get back to this shortly.

I realize you can implement your case without loops but I can see how loops could be useful in the general case. I just need to think through the details of how to get the data flowing correctly without breaking any existing code.

**Comment by fcr** [comment]
Your general case is making regions and phases more powerful and flexible. It is definitely worth the investment. 
Until you get the time to finish your change, my quick and dirty is enough to let me advance.

**Comment by dkeeney** [comment]
Ok, I think it is ready for review.

The biggest things are the addition of 'phase' to addRegion() and run().
It also changed the way data is distributed over the links.  The data is sent just after when the source region is executed.  Previously it was moved just before the destination region was executed.  I don't think this will break anyone but we shall see.
I also added 'mode' to the link parameters so in a link the destination buffer can be overwritten in the fanIn case.

I added a lot more documentation for NetworkAPI.
There was a lot more testing.  Found that the delay was not working quite right and had to fix that...and the tests associated with it.

**Comment by fcr** [comment]
@dkeeney . My use case runs fine under your changes.

**Comment by dkeeney** [comment]
@fcr, thank you for checking.  :)

**Review by ctrl-z-9000-times — APPROVED** [review]
This looks fine to me.

Good work writing the documention and test cases!

**Comment by fcr** [comment]
@dkeeney, thank you for adding this feature.

**Pull request merged**
