### PR TITLE
fix include headers in binary package

### PR DESCRIPTION
**Pull request by breznak**
Fixes for #626

### CODE REVIEW

**Comment by breznak** [comment]
@dkeeney please review, 

> In the include files contained in the binary release,
`#define HTM_CORE_VERSION "4b46e1c62d45bae3794fd05fac6ce8a72adda401"`
I expected this to be 2.0.0 or something. This also shows up in the filename for the distribution.
There should be something in the travis.yml that pushes the version to the file named Version before the build starts. 

could `make package` write the Version.hpp? That would be CI-independent. Should be as follows: 
- if `git tag` -> use that
- otherwise use git commit SHA

**Comment by breznak** [comment]
Also in #629 , is that one correct?

**Comment by breznak** [comment]
Re-starting OSX CI builds

**Comment by dkeeney** [comment]
> could make package write the Version.hpp? That would be CI-independent.

Yes, I am working on this.  Not quite working yet.  It seems that windows and Linux generate slightly different things for `git describe --tags`   But they may be similar enough to work.

**Comment by breznak** [comment]
> Yes, I am working on this. 

perfect :+1: 

> Not quite working yet. It seems that windows and Linux generate slightly different things for git describe --tags But they may be similar enough to work.

might not be needed, in #631 I'm working towards OSX,Win CI upload only the artifacts to CI, and Travis would be responsible for the GH deployment for all 3 of them. 

So if that helps, enough would be writing it from linux only. (unless its needed for the py setup?)

**Comment by dkeeney** [comment]
> So if that helps, enough would be writing it from linux only. (unless its needed for the py setup?)

the wheel needs the version inbedded in it.
I think we need the version Major.Minor.Patch at the point that the package is constructed.

**Comment by breznak** [comment]
@dkeeney can I merge this?

**Comment by dkeeney** [comment]
yes you can merge.

**Comment by dkeeney** [comment]
thank you.

**Pull request merged**
