### PR TITLE
Continuation of fixes for Pickled networkAPI

### PR DESCRIPTION
**Pull request by dkeeney**
This continues work for issue #732

In this PR are the following fixes:
- PyBindRegion: create the Spec for restored Region implementation.
- PyRegion.py: Corrected the import deprecation for importing ABCMeta.
- pyregion_test: removed two tests that no longer apply after correcting the ABCMeta deprecation.
- setup.py: Touch bindings/py/cpp_src/CmakeLists.txt so .py sources are always copied into Release/distr/src.
- Network, Region classes: Moved Phase serialization from Region to Network.
- RegionImplFactory: Made class registrations global for all instances of Network in a process.
- L46aNetwork_test:  A non-trivial unit test that uncovered the above problems.
- NuPIC class: Removed...should have been removed in a previous PR.

### CODE REVIEW

**Comment by dkeeney** [comment]
> why do you delete the function setPhases()?

I did not.   what was removed was the setPhases() from the Region which is an internal function called by the setPhases( ) function on the Network object. A user should still set phases on the Network object rather than on the Region.

**Comment by Thanh-Binh** [comment]
@dkeeney I really do not understand. A region must have a possibility to set its phases independing on other regions in the network. It may have multiple phases for running like L6a for handling sensory or motor input data

**Comment by dkeeney** [comment]
Only the Network object needs to know about phases.  The Network class has a vector for each of the phases and each phase contains a set of pointers to the Regions which are to be called when the phase is executed by the Network class.

What we had before was phase information was contained in both the Network class and the Region class and they had to be kept in synch.  The Region was handling the serialization and then setting the Network with the info.  But the Region never uses that information directly.  

What I did was let the Network handle the Phases entirely.

This does not change the API.  Applications still call Network.setPhase( ) to set the phase(s) in which a Region should be executed, or take the default which is a phase in the order in which the Region is declared.

**Comment by Thanh-Binh** [comment]
@dkeeney best thanks for your explain. Now, it looks nice for me...

**Comment by fcr** [comment]
@dkeeney  my code now also works. Thank you for your support.

**Pull request merged**
