### PR TITLE
Expose the useApicalTiebreak option in ApicalTMSequenceMemory

### PR DESCRIPTION
**Pull request by fcr**
Expose the useApicalTiebreak option in ApicalTMSequenceRegion and memory.
Just a simple change that may be useful to users of the ApicalTMSequenceMemory

### CODE REVIEW

**Comment by ctrl-z-9000-times** [comment]
Hi,

I'm not very familiar with this piece of code, but it seems like you could just set `apicalInputSize=0` to effectively disable the apical input. Would that be equivalent to setting `useApicalTiebreak=False` ?

**Comment by fcr** [comment]
> I'm not very familiar with this piece of code, but it seems like you could just set `apicalInputSize=0` to effectively disable the apical input. Would that be equivalent to setting `useApicalTiebreak=False` ?

No. The flag enables or disables excutable code independent of of apicalInputSize

**Comment by dkeeney** [comment]
@fcr, we cannot do builds right now.  Without a build and unit tests we cannot be sure something is not adversely affected by a PR so we should not merge it in.  I think @breznak is looking for a solution to the builds.

**Comment by ctrl-z-9000-times** [comment]
Would it be possible (and also a good idea) to make it so that `apicalInputSize==0` implicitly disables the feature?

My concern with this PR is that the user could write obviously broken code:
```
ApicalTiebreakTemporalMemory(
    apicalInputSize = 1000,     # User wants apical input,
    useApicalTiebreak = False,  # But the apical input is ignored.
    ...
)
```

But if instead we keep `useApicalTiebreak` private and change its value to:
`useApicalTiebreak = (apicalInputSize==0)`

Then it should by construction be impossible to make that mistake.

**Comment by fcr** [comment]
@ctrl-z-9000-times, there is possible use case where one has a model that has connections to the apical input (i.e. `apicalInputSize > 0`) but may want to control when that input is to be used and when it is not. The original Numenta  research implementation provides  similar control for `useApicalModulationBasalThreshold`.
I have modified my push request such that `apicalInputSize` is no longer an argument but preserved method access for it to make it consistent with `useApicalModulationBasalThreshold`.

**Comment by ctrl-z-9000-times** [comment]
Okay thanks, that use-case makes sense!

**Review by ctrl-z-9000-times — APPROVED** [review]
@fcr Have you run the unit tests on this?
Use the command:
`pytest py/tests/advanced/algorithms/apical_tiebreak_temporal_memory/`

If all those tests pass on your branch, then I will go ahead and merge this.

**Comment by fcr** [comment]
All tests passed. :-)

**Pull request merged**
