### PR TITLE
Fixed some nits in distribution.

### PR DESCRIPTION
**Pull request by dkeeney**
fixed the extra 'src' folder level in include of distribution. 
Fixed "Python 2" in setup.py

### CODE REVIEW

**Comment by breznak** [comment]
Re-starting OSX CI builds

**Comment by breznak** [comment]
Close?

**Comment by dkeeney** [comment]
did this ever get merged...  apparently not.
Let me merge in master and re-submit

**Comment by breznak** [comment]
I think the code is covered/merged in prev PRs

**Comment by dkeeney** [comment]
The changes in this PR were merged already in another PR.  So ignore this one.

**Pull request closed without merging**
