### PR TITLE
Simhash document encode [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by breznak**
only for running CI tests to help #603 , close after tests finish
FYI @brev

### CODE REVIEW

**Comment by breznak** [comment]
@brev there are a couple of bugs for RDSE introduced by this PR, and an issue w SimHash

**Comment by breznak** [comment]
@brev OSX CI is still failing

> [----------] 12 tests from SimHashDocumentEncoder
[ RUN      ] SimHashDocumentEncoder.testBasicExampleUseCase
Assertion failed: (index >= 0 && index < size()), function operator(), file /Users/distiller/numenta/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/DenseCoeffsBase.h, line 425.
Received 'abort trap' signal

seems not directly related to your code, but something in Eigen that the code uses? See if there's a newer release of Eigen? Or what is the problem in Debug?

**Comment by brev** [comment]
uh, yikes, no idea - looking now.

**Comment by breznak** [comment]
This is all passing now :trumpet:

**Comment by breznak** [comment]
This is all passing now :trumpet:

**Pull request closed without merging**
