### PR TITLE
Revert experimential changes to the anomaly likelihood.

### PR DESCRIPTION
**Pull request by ctrl-z-9000-times**
I tried to improve the anomaly detection by looking at multiple consecutive anomaly readings and combining them.

Initially I saw some limited improvements, but after further thought I think this was a mistake.

This should fix issue #960

### CODE REVIEW

**Comment by dkeeney** [comment]
@ctrl-z-9000-times do you know how to get the builds running again?  I don't have a clue and I have not seen @breznak for a while.

**Comment by ctrl-z-9000-times** [comment]
I'm assuming you mean the pypi release builds?

I've released other packages on pypi before, but not this package.

There is a script that does the work.
It triggers  when github "tags" a commit with a version number?
It should be mostly already setup from the previous releases.
But the dependency versions will need updating.

README: https://github.com/htm-community/htm.core/blob/master/RELEASE.md
SCRIPT: https://github.com/htm-community/htm.core/blob/master/.github/workflows/release.yml

**Comment by dkeeney** [comment]
I expected that this PR would have automatically ran the four builds but it does not seem to have started. 
@breznak gave me admin privs but I have no clue where to start looking for the cause.

**Review by dkeeney — APPROVED** [review]
No problem

**Comment by ctrl-z-9000-times** [comment]
Thanks for reviewing this.
I'm going to go ahead an merge this one without CI.

**Pull request merged**
