### PR TITLE
Fixed incorrect performance optimization, that was losing valid data.

### PR DESCRIPTION
**Pull request by fcr**
This is an additional change to the location_module package. Seems that assume_unique was an invalid assumption.

### CODE REVIEW

**Review by dkeeney — COMMENTED** [review]
All changes must have a unit test that proves that it works.
Otherwise I don't have a problem with this.  @ctrl-z-9000-times should also look at it to make sure it makes since in the algorithm.

**Comment by fcr** [comment]
It will be extremely hard to set up a simple test that catches this particular case, since up to now I have not hit a case where it there was a problem. I simply noticed that the assume_unique flag in this particular code should not be there. (a case of copy and paste from other `htmresearch` code that I ported where assume_unique was an effective optimization.)

**Review by ctrl-z-9000-times — APPROVED** [review]
This looks good to me.
I'm not actually familiar with the code in the `advanced/` directory,
but removing the assume_unique flag should not cause any problems.

**Comment by dkeeney** [comment]
Ok, I will approve it and merge it in.

**Comment by dkeeney** [comment]
@fcr, thanks for taking the time to fix this.

**Pull request merged**
