### PR TITLE
Replace htm/utils/GroupBy with simpler in-lined implementation.

### LINKED ISSUE #973: result_of deprecated
This issue was reported on the forum:
https://discourse.numenta.org/t/nupic-installation-on-macos-12-0-error/9410/8

```
[  4%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/algorithms/TemporalMemory.cpp.o
In file included from /htm.core/src/htm/algorithms/TemporalMemory.cpp:44:
/htm.core/src/htm/utils/GroupBy.hpp:95:71: error: 'result_of<(lambda at /htm.core/src/htm/algorithms/TemporalMemory.cpp:296:25) (const unsigned int &)>' is deprecated [-Werror,-Wdeprecated-declarations]
          typename KeyType = typename std::remove_const<typename std::result_of<
                                                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/type_traits:4009:34: note: 'result_of<(lambda at /htm.core/src/htm/algorithms/TemporalMemory.cpp:296:25) (const unsigned int &)>' has been explicitly marked deprecated here
template <class _Callable> class _LIBCPP_DEPRECATED_IN_CXX17 result_of;
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
[  4%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/encoders/DateEncoder.cpp.o
[  5%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/encoders/ScalarEncoder.cpp.o
1 error generated.
make[2]: *** [src/CMakeFiles/LibrarySource.dir/htm/algorithms/TemporalMemory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/LibrarySource.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/htm.core/setup.py", line 414, in <module>
    getExtensionFiles(platform, build_type)
  File "/htm.core/setup.py", line 241, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "/htm.core/setup.py", line 305, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type, "--", "-j", "4"]) 
  File "/opt/anaconda3/envs/htm.core/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.
```

### PR DESCRIPTION
**Pull request by ctrl-z-9000-times**
Fixes #973

This branch passes the *relevant* unit tests on linux in both debug and release mode.

Unrelated to this PR, `algorithms/anomaly_likelihood_test.py` is failing probably because of the most recent PR I merged to that code.

### CODE REVIEW

**Comment by finnoshea** [comment]
FYI, this still doesn't compile for me on OSX 12.3.  There is another ```result_of``` in there.


```
[  7%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/engine/Input.cpp.o
In file included from /htm.core/src/htm/encoders/SimHashDocumentEncoder.cpp:30:
/htm.core/build/ThirdParty/digestpp/digestpp-src/hasher.hpp:136:10: error: variable 'len' set but not used [-Werror,-Wunused-but-set-variable]
                size_t len = 0;
                       ^
In file included from /htm.core/src/htm/encoders/SimHashDocumentEncoder.cpp:34:
In file included from /htm.core/src/htm/encoders/SimHashDocumentEncoder.hpp:27:
In file included from /htm.core/build/ThirdParty/eigen/eigen-src/Eigen/Dense:1:
In file included from /htm.core/build/ThirdParty/eigen/eigen-src/Eigen/Core:367:
/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/util/Meta.h:320:25: error: 'result_of<Eigen::internal::scalar_cmp_op<int, int, Eigen::internal::cmp_EQ> (const int &, const int &)>' is deprecated [-Werror,-Wdeprecated-declarations]
  typedef typename std::result_of<T>::type type1;
                        ^
/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/CwiseBinaryOp.h:33:20: note: in instantiation of template class 'Eigen::internal::result_of<Eigen::internal::scalar_cmp_op<int, int, Eigen::internal::cmp_EQ> (const int &, const int &)>' requested here
  typedef typename result_of<
                   ^
/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/util/XprHelper.h:497:56: note: in instantiation of template class 'Eigen::internal::traits<Eigen::CwiseBinaryOp<Eigen::internal::scalar_cmp_op<int, int, Eigen::internal::cmp_EQ>, const Eigen::ArrayWrapper<Eigen::Matrix<int, -1, 1, 0>>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>, Eigen::Array<int, -1, 1, 0>>>>' requested here
template<typename Derived, typename XprKind = typename traits<Derived>::XprKind, typename StorageKind = typename traits<Derived>::StorageKind>
                                                       ^
/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/CwiseBinaryOp.h:149:22: note: in instantiation of default argument for 'generic_xpr_base<Eigen::CwiseBinaryOp<Eigen::internal::scalar_cmp_op<int, int, Eigen::internal::cmp_EQ>, const Eigen::ArrayWrapper<Eigen::Matrix<int, -1, 1, 0>>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>, Eigen::Array<int, -1, 1, 0>>>>' required here
  : public internal::generic_xpr_base<CwiseBinaryOp<BinaryOp, Lhs, Rhs> >::type
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/CwiseBinaryOp.h:78:10: note: in instantiation of template class 'Eigen::CwiseBinaryOpImpl<Eigen::internal::scalar_cmp_op<int, int, Eigen::internal::cmp_EQ>, const Eigen::ArrayWrapper<Eigen::Matrix<int, -1, 1, 0>>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>, Eigen::Array<int, -1, 1, 0>>, Eigen::Dense>' requested here
  public CwiseBinaryOpImpl<
         ^
/htm.core/src/htm/encoders/SimHashDocumentEncoder.cpp:241:30: note: in instantiation of template class 'Eigen::CwiseBinaryOp<Eigen::internal::scalar_cmp_op<int, int, Eigen::internal::cmp_EQ>, const Eigen::ArrayWrapper<Eigen::Matrix<int, -1, 1, 0>>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>, Eigen::Array<int, -1, 1, 0>>>' requested here
    vector = (vector.array() == 0u).select(-1, vector);
                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/type_traits:4009:34: note: 'result_of<Eigen::internal::scalar_cmp_op<int, int, Eigen::internal::cmp_EQ> (const int &, const int &)>' has been explicitly marked deprecated here
template <class _Callable> class _LIBCPP_DEPRECATED_IN_CXX17 result_of;
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
[  8%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/engine/Link.cpp.o
2 errors generated.
make[2]: *** [src/CMakeFiles/LibrarySource.dir/htm/encoders/SimHashDocumentEncoder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/LibrarySource.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/htm.core/setup.py", line 414, in <module>
    getExtensionFiles(platform, build_type)
  File "/htm.core/setup.py", line 241, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "/htm.core/setup.py", line 305, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type, "--", "-j", "4"]) 
  File "/opt/anaconda3/envs/htm.core/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.
```

**Comment by ctrl-z-9000-times** [comment]
That's in third party code, so I'm not sure I can fix it.

I think the next best solution is probably to remove the `-Werror` flag.

**Comment by finnoshea** [comment]
I searched all the CMakelists.txt files and couldn't find a single -Werror flag.  Where do I remove it?

**Comment by ctrl-z-9000-times** [comment]
It's here:

CommonCompilerConfig.cmake:282: set (internal_compiler_warning_flags ${internal_compiler_warning_flags} -Werror -Wextra -Wreturn-type -Wunused -Wno-unused-variable -Wno-unused-parameter -Wno-missing-field-initializers)

Pro tip: I used the command `git grep -n Werror` to find this. Git's `grep` sub-command will only search through things that are in version control so it won't look at things in the `/build/` directory or anything filtered out by `.gitignore`.

**Comment by finnoshea** [comment]
Even after removing the -Werror, it still won't make:

```
[ 35%] Generating htm_core_dummy.c++
[ 35%] Building CXX object src/CMakeFiles/htm_core.dir/htm_core_dummy.c++.o
[ 36%] Linking CXX static library libhtm_core.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libhtm_core.a(htm_core_dummy.c++.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libhtm_core.a(htm_core_dummy.c++.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: libhtm_core.a the table of contents is empty (no object file members in the library define global symbols)
Combining $<TARGET_FILE:htm_core> for target htm_core from $<TARGET_FILE:htm_core_solo>;/htm.core/build/ThirdParty/libyaml/libyaml-build/libyaml.a;/htm.core/build/ThirdParty/libsqlite3.a;/htm.core/build/ThirdParty/libcommon.a.
-- COMBINE_UNIX_ARCHIVES(  LIB_TARGET=htm_core,   TARGET_LOCATION=/htm.core/build/scripts/src/libhtm_core.a,   SRC_LIB_LOCATIONS=/htm.core/build/scripts/src/libhtm_core_solo.a++++/htm.core/build/ThirdParty/libyaml/libyaml-build/libyaml.a++++/htm.core/build/ThirdParty/libsqlite3.a++++/htm.core/build/ThirdParty/libcommon.a,   LIST_SEPARATOR=++++,   BINARY_DIR=/htm.core/build/scripts/src,   CMAKE_AR=/Library/Developer/CommandLineTools/usr/bin/ar)
-- COMBINE_UNIX_ARCHIVES: LIB_TARGET=htm_core, src-lib=/htm.core/build/scripts/src/libhtm_core_solo.a
CMake Error at /htm.core/src/CombineUnixArchives.cmake:73 (message):
  COMBINE_UNIX_ARCHIVES: obj extraction process failed exe_result='No such
  file or directory'
Call Stack (most recent call first):
  /htm.core/src/CombineUnixArchives.cmake:123 (combine_unix_archives)


make[2]: *** [src/libhtm_core.a] Error 1
make[1]: *** [src/CMakeFiles/htm_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 36%] Linking CXX executable dynamic_hello
[ 36%] Built target dynamic_hello
make: *** [all] Error 2
Traceback (most recent call last):
  File "/htm.core/setup.py", line 414, in <module>
    getExtensionFiles(platform, build_type)
  File "/htm.core/setup.py", line 241, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "/htm.core/setup.py", line 305, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type, "--", "-j", "4"]) 
  File "/opt/anaconda3/envs/htm.core/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.
```

**Comment by ctrl-z-9000-times** [comment]
Sorry, I can't help you with that error.
The only thing I can think to do is to delete the  build directory and try a clean build.

**Comment by ctrl-z-9000-times** [comment]
Hi @dkeeney,
This is ready for review when you get the time.

This removes the "groupby" utility, which was a rather complicated piece of template code.
It was used exactly one in htm.core so I re-implemented it in-line.

**Review by dkeeney — CHANGES_REQUESTED** [review]
If I understand the code correctly, you removed the GroupBy code and rewrote it in-line in TemporalMemory.cpp.  So the feature still exists. But you also removed the unit test.  Are there other tests that cover this feature?

**Comment by ctrl-z-9000-times** [comment]
Yes, the temporal memory still has many test cases.

The functionality of the GroupBy code can't be tested independently anymore, because I inlined it.
Also, the code is much simpler now (without C++ templates) and I've added comments to explain what it does.

**Review by dkeeney — APPROVED** [review]
Ok, I will approve and merge it into the master.

**Comment by dkeeney** [comment]
Hmmm, I have a problem with the Windows build.
(Building on Windows 11, Python 3.9, Visual Studio 2022)
```
algorithms\anomaly_likelihood_test.py::ArtificialAnomalyTest::testCaseIncreasedSpikeFrequency FAILED             [ 67%]
algorithms\anomaly_likelihood_test.py::ArtificialAnomalyTest::testCaseSingleSpike PASSED                         [ 68%]
algorithms\anomaly_likelihood_test.py::ArtificialAnomalyTest::testCaseUnusuallyHighSpikeFrequency FAILED         [ 69%]
```
I think this may have showed up after the previous PR.
@ctrl-z-9000-times does this show up in the Linux build?

**Comment by ctrl-z-9000-times** [comment]
@dkeeney,

Yes, those failures show up on the linux build.
Those failures are unrelated to this PR.

I think I introduced those failures when I reverted a change that I did to the anomaly likelihood detector, in PR #962.
I'm going to work on fixing those tests next.

**Pull request merged**
