### PR TITLE
bump dependency versions

### PR DESCRIPTION
**Pull request by breznak**
use latest versions for our 3rd party deps

### CODE REVIEW

**Comment by breznak** [comment]
All tests passing with the new deps! :+1:

**Comment by dkeeney** [comment]
Thanks for bumping the versions on the dependencies.

**Comment by breznak** [comment]
> the dependencies. 

if you like, could you please have a look at google/gtest-10.0 ? It's not a very high priority, but would be nice to have 1+yr of improved warnings. I wasn't able to build the new 10.0 version in cmake

**Comment by dkeeney** [comment]
Ok, I will take this one.

**Pull request merged**
