### PR TITLE
Use python 3.8 in CI builds

### LINKED ISSUE #734: Unable to install numpy from source on Python 3.8
I just installed Python 3.8 on windows 10.   I set my system environment path to include the path to Python 3.8.  This seemed to be a good time to install with a 'virgin' system.
So I then tried a python build, i.e.  `python setup.py install --user --force`

It seemed to find setuptools without having to install before hand. So perhaps setuptools is now part of the core.

While building the egg, it was able to find and install 
- prettytable 0.7.2
- mock 3.0.5
- hexy 1.4.3
- pytest 4.6.5
- numpy 1.17.3  downloaded .zip but failed for lack of a Fortran compiler
```
C:\Users\Dave\AppData\Local\Temp\easy_install-yzk_o6bt\numpy-1.17.3\setup.py:418: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
Could not locate executable g77
Could not locate executable f77
Could not locate executable ifort
Could not locate executable ifl
Could not locate executable f90
Could not locate executable efl
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable g95
Could not locate executable efort
Could not locate executable efc
Could not locate executable flang
don't know how to compile Fortran code on platform 'nt'
```

Everything fell apart after that...

### PR DESCRIPTION
**Pull request by breznak**
All PRs CI use py3.8, for releases we provide 3.7, 3.8. 

Fixes #734 #809

### CODE REVIEW

**Comment by breznak** [comment]
linux py3.8 tests fail, 
https://github.com/htm-community/htm.core/pull/820/checks?check_run_id=731129639#step:9:1053 

strangely, I cannot replicate that locally on 20.04.

**Comment by breznak** [comment]
I don't know why tests would start failing to import on Py3.8

**Review by breznak — COMMENTED** [review]
@dkeeney this is now passing, please review Py3.8 support.

**Review by dkeeney — APPROVED** [review]
Ok, I understand what the change is.  I centers the expected result better within the 0.003 allowance.
Did you confirm it did not break 3.7?

**Comment by breznak** [comment]
>  centers the expected result better within the 0.003 allowance. 

this is just a fix for the prev merged PR for RDSE params_check(), which has random behavior - and on OSX I randomly failed the assert. As adviced, I increased the SDR size (so conflicts are more rare) and that changed the results. 

> Did you confirm it did not break 3.7? 

The test didn't. But now we fully test only on py3.8. Do we want to keep some platform on 3.7 to cover both? Good idea.

**Comment by dkeeney** [comment]
Will, even if you manually checked it with 3.7 it would be ok.

**Comment by breznak** [comment]
>  Do we want to keep some platform on 3.7 to cover both?  

@dkeeney merged as is now, so we run everything on py3.8, do we want to keep, say OSX on 3.7?

**Comment by dkeeney** [comment]
I think it should be sufficient if we manually check 3.7 locally before we check it in.  We should only need to do that for a short while.

**Pull request merged**
