### PR TITLE
Changed prune segments to use a heuristic based on the synapse permanences.

### PR DESCRIPTION
**Pull request by ctrl-z-9000-times**
Hi,

I ran into an issue with the method `Connections::pruneLruSegment_`. My program learns with the TM for a while, and then the inputs are interrupted with random noise, and when the normal input returns all of the segments are gone. Here is what happened:
1) Normal inputs are given to the TM and the TM learns a bunch of stuff.
2) The inputs are interrupted with random noise for at least 50 timesteps.
3) When the TM fails to predict the inputs, then it makes new segments to learn the current input. Random inputs are unpredictable so when they are presented the TM creates new segments.
4) The random inputs cause the TM to reach its maximum number of segments, at which point it will need to deletes a segment.
5) The Least Recently Used segments are removed, which are all of the old segments from the beginning of the experiment. But those old segments were the only segments which had actually learned anything!

My solution is to replace "Least Recently Used" with "Least Useful" and then I invented a heuristic to determine how useful a segment is.
> Heuristic = sum(synapse.permanence ^ power for synapse on segment)

Where power is a positive integer.
This heuristic favors keeping segments which have many strong synapses over segments with fewer or weaker synapses.

This appears to work for me, but before it's merged I'd really like to see a before/after comparison on NAB.

### CODE REVIEW

**Comment by ctrl-z-9000-times** [comment]
I ran NAB on this branch.

Here are the results as advertised on the NAB webpage: https://github.com/htm-community/NAB
Standard 	63.1
low FP 	58.8
low FN	66.2

Here are the scores on my branch `master`
Final score for 'htmcore' detector on 'standard' profile = 62.82
Final score for 'htmcore' detector on 'reward_low_FP_rate' profile = 58.84
Final score for 'htmcore' detector on 'reward_low_FN_rate' profile = 66.02
Final scores have been written to /home/dm/NAB/results/final_results.json.
user time	64m21.149s

Here are the scores on my branch `prune-segment2`
Final score for 'htmcore' detector on 'standard' profile = 63.14
Final score for 'htmcore' detector on 'reward_low_FP_rate' profile = 59.53
Final score for 'htmcore' detector on 'reward_low_FN_rate' profile = 66.19
user time	45m31.242s

I think that the differences in thes scores are insignificant.

---

I also measured the run time of both branches:
master branch: 64m21.149s
this branch: 45m31.242s

These times are the total CPU time, from all threads of execution.
Note: on my computer I updated this branch with the latest changes from master.

I think that the performance gain is because this change allowed me to remove some book-keeping variables, which as breznak pointed out are actually quite expensive to keep.

**Comment by dkeeney** [comment]
Resolve the conflict with Connections.cpp and I will approve it.   Thanks.

**Comment by ctrl-z-9000-times** [comment]
Ok, I fixed the merge conflict.
Thanks for reviewing this.

**Review by dkeeney — APPROVED** [review]
Looks good.
Thanks for doing this.

**Comment by breznak** [comment]
Sorry I'm getting back to this only this late...very nice change, thank you @ctrl-z-9000-times ! 

I especially like this change from the biological aspect,
> [replace] with "Least Useful" and then I invented a heuristic to determine how useful a segment is.

where manually remembering 'last access time' was somewhat artificial; I think this also (almost fully) implements the "energy-based, or prune by starving hungry" cells approach I was proposing, so I'm glad you managed to find a good heuristic of "usefulness" of a segment. 

The improvements on the NAB performance are quite remarkable, and the speed boost is huge! :100: 
(we should revisit htmcore's NAB scores some time and try to finally beat nupic :wink: )

**Comment by ctrl-z-9000-times** [comment]
> the speed boost is huge!

I know right! that surprised me.

**Pull request merged**
