### PR TITLE
Travis bionic

### LINKED ISSUE #598: Travis CI switch to bionic
Ubuntu Bionic images are recently available in Travis, which is nice since Xenial was getting old. 
https://travis-ci.com/Farwaykorse/test_Travis_CMake/jobs/213737431#L18

use `dist: bionic` in `.travis.yml` to switch. No need to use PPA for gcc-8 then, which is packaged in the distro. 

Question: do we want to test in the CI python2, or switch to py3?

### PR DESCRIPTION
**Pull request by breznak**
- [x] Travis CI switches to Ubuntu Bionic
- [x] Python tested bumped to 3
- [x] (try w/o apt-update)

Fixes #598

### CODE REVIEW

**Comment by breznak** [comment]
https://docs.travis-ci.com/user/languages/python/

this is info on the PY environment in Travis.

**Comment by breznak** [comment]
Seems the pybind11 is picking up python3.7, while I want to use default, installed py3.6: 

```
cpp-build/libyaml-cpp.a

-- ExpandStaticLib: LIB_TARGET=htm_core_shared, src-lib=/home/travis/build/htm-community/htm.core/build/ThirdParty/libcommon.a

-- Configuring htm_core tests

-- Configuring Python interface

-- Found PythonInterp: /opt/pyenv/shims/python3.7 (found version "1.4") 

CMake Error at build/ThirdParty/pybind11/pybind11-src/tools/FindPythonLibsNew.cmake:95 (message):

  Python config failure:

  pyenv: python3.7: command not found

  

  The `python3.7' command exists in these Python versions:

    3.7.1

  

Call Stack (most recent call first):

  build/ThirdParty/pybind11/pybind11-src/tools/pybind11Tools.cmake:16 (find_package)

  build/ThirdParty/pybind11/pybind11-src/CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!

See also "/home/travis/build/htm-community/htm.core/build/scripts/CMakeFiles/CMakeOutput.log".

Traceback (most recent call last):

  File "/home/travis/build/htm-community/htm.core/setup.py", line 53, in <module>

    runpy.run_path(__file__, run_name=__name__)

  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 263, in run_path

    pkg_name=pkg_name, script_name=fname)

  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 96, in _run_module_code

    mod_name, mod_spec, pkg_name, script_name)

  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/home/travis/build/htm-community/htm.core/bindings/py/packaging/setup.py", line 254, in <module>

    getExtensionFiles(platform)

  File "/home/travis/build/htm-community/htm.core/bindings/py/packaging/setup.py", line 179, in getExtensionFiles

    generateExtensions(platform)
```
https://travis-ci.org/htm-community/htm.core/builds/569759689#L957

It works on my local machine with Bionic, where I don't have python3.7 

CC @dkeeney any idea why is this happening?

**Comment by breznak** [comment]
There are 2 possible workaround: 
- I can switch back to py2.7 and only switch to Bionic as part of this PR
- I could force py3.7 which is available in the CI
  - I'll likely do that if we don't figure this, 
  - would just like to know why the pybind picks a wrong python version?

**Comment by ctrl-z-9000-times** [comment]
My guess is that the CI system comes with python 3.7 already installed, and your request for python 3.6 will install it but does not override the system installation.  The system installation of python likely installed under the name `python3.7` and then added symlinks from `python -> python3.7`.  Your installation of python3 only installs `python3.6` but did not alter the symlinks in `/usr/bin/` to point to the new version so when pybind11 looks for the default python it finds the symlink to 3.7.

I'm running a different version of ubuntu, and my `/usr/bin/` is also setup with symlinks from `python` -> `python3.X`

**Comment by breznak** [comment]
> My guess is that the CI system comes with python 3.7 already installed, and your request for python 3.6 will install it but does not override the system installation. The system installation of python likely installed under the name python3.7 

Hmm, I think bionic comes with 3.6, but let’s go for KISS, trying with 3.7 python

**Comment by breznak** [comment]
Newer pytest resolves the problem 
This is now ready, when you have time

**Comment by breznak** [comment]
> I'm assuming that we still have test coverage of python2 with one of the other CI systems? 

python 2 still runs on OSX CI, but actually my plan was to get rid of it too in #615 . My plan was for a slow obsoletion, 3.5mo for py2 to live, I thought we'd get all the CI running on py3, but still keep the py2 support intact. Thoughts?

**Pull request merged**
