### PR TITLE
Changed SPRegion "synPermConnected" parameter access from ReadOnly to

### PR DESCRIPTION
**Pull request by fcr**
Wanted to make sure that this didn't fall between the cracks.
Also, I need this right now.
Please note that I enabled the test for this in the pyBind tests
Good to see that CreateAccess in the .cpp code works as advertised. :-)

### CODE REVIEW

**Comment by fcr** [comment]
Please merge now.
The pyBind breaks with the Create access. This has been flagged as a bug [#669](https://github.com/htm-community/htm.core/issues/669).
The new regions run since they (as a workaround) use ReadWrite access where there should be Create

**Comment by breznak** [comment]
> The pyBind breaks with the Create access. This has been flagged as a bug #669.

I know, that's why I'm surprised `CreateAccess` works for you in this case (?)

**Comment by fcr** [comment]
> > The pyBind breaks with the Create access. This has been flagged as a bug #669.
> 
> I know, that's why I'm surprised `CreateAccess` works for you in this case (?)

In this PR it is in your c++ code.

**Comment by breznak** [comment]
> In this PR it is in your c++ code.

yeah, I thought CreateAccess is broken overall. So the problem is only for python regions, "advanced.regions" ?

**Comment by fcr** [comment]
So it appears.

**Comment by fcr** [comment]
If you change any of the "ReadWrite" parameters to "Create", and try to initialize that parameter, you get the same error as it had "ReadOnly" access.

**Pull request merged**
