### PR TITLE
CI PyPI cibuildwheel

### PR DESCRIPTION
**Pull request by breznak**
- [x] separate workloads into standalone files: PR, ARM, release
- [x] use `cibuildwheel` to generate wheels on all platforms

### CODE REVIEW

**Comment by breznak** [comment]
@dkeeney the build passes, I'm merging this to be able to test the release/tag workflow...

**Comment by breznak** [comment]
for #802

**Comment by dkeeney** [comment]
Looks good

**Comment by breznak** [comment]
Thanks @dkeeney , 
- as you can see, I'm playing with https://pypi.org/project/cibuildwheel/ , it looks promising to resolve our PyPI releases once for all. 
- FYI, reading on the topic, I learned about "python limited API" `Py_LIMITED_API` which allows you to run on any(*) 3.x version. https://docs.python.org/3/c-api/stable.html    If we could easily do that, that would be a huge win. 
- our py3.8 still sucks :( 

PS: sorry, there will be a lot of merged PRs and commits today, as I'm debugging the release logic

**Pull request merged**
