### PR TITLE
Removed the limit on the number of phases

### PR DESCRIPTION
**Pull request by fcr**
I have an application that needs some regions to run multiple times before then next region runs. The easiest (and most flexible) way to express this within the network framework is to assign the region to a (large) number of phases.
The master version of `setPhases` prevents this.
This pull request simply removes the limit.

### CODE REVIEW

**Comment by dkeeney** [comment]
I am traveling this weekend but this sounds like a reasonable thing to do. I will take a close look when I return on Monday evening.

**Comment by dkeeney** [comment]
I don't think this is doing what you expected it to.  The lines you removed were not intended to limit the number of phases.  It just says don't set a phase number that is larger than the current number of phases.  If it is equal to the size, the size is incremented by one, growing the phaseInfo array by one to make room for the new one.  However, I don't think the check is working correctly either.

I think what you want is to grow the number of phases each time you want to create a new phase.  I think I should try to fix this .... rather than just commenting out the check.

**Comment by dkeeney** [comment]
May I also suggest an alternative to creating a massive number of phases.
What if we added a second optional argument, "phaseID", to the run( ) method that says execute the specified phase?
```
     void run(Uint32 iterations, UInt32 phaseID=0);
```
where the "phaseID" argument is optional, defaulting to 0 which means execute all phases in phase order.

Here is an example of how you might use this...
Assume you have three sets of regions.  
- The first is a set that you want to run to initialize something.  
- The second set of regions does some work and it should be executed 100 times.
- The third set of regions you want to run after the second set has finished its iterations.

Let's say there will be three phases, one for each of the sets above.  The first will be phase ID 1, the second is phase ID 2, the third is phase ID 3.   Remember that phase 0 contains all regions.

So, you first create a Network object.
Then you add all of the regions to the Network object.
Then you add all of the links to connect up all of the data flows.
Then you add each region to each of the phases in which it participates.  A region may be in more than one phase. Note that the order that regions are added to a phase dictates the order of execution within that phase.

Then in your main you call three run's, specifying the phase to execute.  
```
   net.run(1, 1);     // this means, run once but only execute phase ID = 1.
   net.run(100, 2); // this means, run phase ID 2,  100 times.
   net.run(1, 3);     // this means, run phase ID 3, 1 time.
```
Or you could do the iteration in the main code as:
```
   net.run(1, 1);     // this means, run once but only execute phase ID = 1.
   for (int i = 0; i < 100; i++) {
      net.run(1, 2);
   }
   net.run(1, 3);     // this means, run phase ID 3, 1 time.
```
By putting the loop in the main, you can do things like poke data into the encoder on each iteration.  It all depends on what you need to be able to do.

Note that in Python the syntax would be different but I think you get the idea.

If this sounds like a better idea for your application, I will code the changes to NetworkAPI needed to make it work.

**Comment by fcr** [comment]
If I understand your above suggestion, it will not solve my particular scenario.
Say I have 5 regions: A,B,C,D,E. Each cycle I want the following sequence: A,B,C,D,C,D,C,D....C,D,E.
Without the current error check I can set this up with:
```
    network.setPhases("A", set([0])) 
    network.setPhases("B", set([1]))   

    c_phases = [2 + i * 2 for i in range(theta_period)]   
    d_phases = [3 + i * 2 for i in range(theta_period)]   
    network.setPhases("C", set(c_phases))   
    network.setPhases("D", set(d_phases))  

    e_phase = d_phases[-1] + 1
    network.setPhases("E", set([e_phase]))
```   
With the current error check I cannot do this. In fact, because sets are not passed to the C code in order, the current error check will not allow more than the addition of 5 or 7 phases to a region, depending on the scrambling of the set.

**Comment by fcr** [comment]
@dkeeney, thinking more about it. I like your suggestion better.

**Comment by dkeeney** [comment]
> I think that my suggested usage should also be supported.

Yes, I agree.  The logic should have allowed (nearly) unlimited number of phases.  I will work on fixing that.

> I like your suggestion better

Ok, I will implement that as well.   This will take me a few days.

**Comment by dkeeney** [comment]
Oh, in your scenario using regions A, B, C, D, E.... I would put regions C and D in the same phase and iterate that phase after executing the phase containing B and before executing the phase containing E.

**Comment by fcr** [comment]
D has to process the output of C at each iteration. Hence it has to have a higher phase.

**Comment by dkeeney** [comment]
Yes, it still works.  When a phase containing C and D is executed, it will execute them in the order in which they were added.  So C executes and its output is available for D when it executes.  The output of D will be available to E whenever it executes in the final phase.

**Comment by fcr** [comment]
Great. If that is guaranteed, then that simplifies things.

**Comment by dkeeney** [comment]
Well, guarantees are hard to obtain when writing software, but I will do my best.

**Review by dkeeney — APPROVED** [review]
I am going to approve this PR because this is the first step that must be performed to fix the phases.  Removing the check will allow more than 3 new phases to be added to the network at the same time with setPhase( ).

I will generate a subsequent PR which will add a second argument to the run( ) method which specifies a phase to execute.  With that PR I will include unit tests and documentation for this PR.

**Pull request merged**
