### PR TITLE
Gtest update to  version10.0

### PR DESCRIPTION
**Pull request by dkeeney**
Gtest moved the default location for its generated libraries.
So this PR bumps the gtest version and correctly locates the generated libraries so that CMake can build the unit tests.

### CODE REVIEW

**Comment by dkeeney** [comment]
Hmmm, debug unit test appears to be taking too long.  Are there any tests we can shorten for debug mode?

**Review by breznak — APPROVED** [review]
Thank you, David! :+1: 
Let's see if the Debug passes, rerunning

**Comment by breznak** [comment]
> Hmmm, debug unit test appears to be taking too long. Are there any tests we can shorten for debug mode? 

it seems to me the tests didn't even start, just the CI somehow borked. Re-running
(I think most tests are already "trivialized" for Debug to take almost no time)

**Comment by breznak** [comment]
> it seems to me the tests didn't even start, just the CI somehow borked 

yep, all completed fine! thank you

**Pull request merged**
