### PR TITLE
2X Speedup of ColumnPooler when learning.

### PR DESCRIPTION
**Pull request by fcr**
Discovered these changes using the [Scalene](https://github.com/plasma-umass/scalene) profiler.
The additions to connections.py can be ported to Connections.cpp for an additional boost in performance.
My C++ is too rudimentary to do so myself.

### CODE REVIEW

**Review by dkeeney — APPROVED** [review]
I find nothing in the code that I object to but I will have to rely on you that it runs correctly.

**Comment by dkeeney** [comment]
Fred, we lost access to our build process so I cannot automatically verify the unit tests.
If you ran them and everything passed, I can bypass the build requirement and manually merge your changes

**Comment by fcr** [comment]
> Fred, we lost access to our build process so I cannot automatically verify the unit tests. If you ran them and everything passed, I can bypass the build requirement and manually merge your changes

I ran them all on my MacBook Pro and they all passed. I don't have any other platforms with which to check.

**Comment by dkeeney** [comment]
Ok, merging in your request.

**Pull request merged**
