### PR TITLE
Changed some Region and example names.

### PR DESCRIPTION
**Pull request by dkeeney**
See Issue #784 
Changed the following Region names:
- RDSERegion --> RDSEEncoderRegion
- ScalarSensor --> ScalarEncoderRegion
- VectorFileEffector --> FileOutputRegion
- VectorFileSensor --> FileInputRegion

Changed the following Example names:
-  src/examples/hotgym/Hotgym.cpp  --> src/examples/hello/Hello.cpp
- src/examples/napi_sine/napi_sine.cpp --> src/examples/napi_hello/napi_hello.cpp

### CODE REVIEW

**Comment by dkeeney** [comment]
@breznak  Could you fix the push build to look for executable "hello" rather than "benchmark_hotgym" for valgrind in the ubuntu build.    
Thanks.

**Comment by breznak** [comment]
> Could you fix the push build to look for executable "hello" rather than "benchmark_hotgym" for valgrind in the ubuntu build. 

@dkeeney I can do it later (have some uncommited changes). Otherwise, it's in `.github/workflow/build.yml`

**Comment by dkeeney** [comment]
> Otherwise, it's in .github/workflow/build.yml

Ah, did not think to look there.   I can do it.

**Comment by breznak** [comment]
@dkeeney would it make sense (now not so much yet) to make a minor-version bump (tag) on each API breaking change?

**Comment by dkeeney** [comment]
> to make a minor-version bump

Yes, I was thinking that would be a good idea.  Let me finish the Python REST example first.

**Pull request merged**
