### PR TITLE
initialized the array per issue #908

### PR DESCRIPTION
**Pull request by dkeeney**
Initialized the array in the SP bindings and added a few minor fixes to warnings.

### CODE REVIEW

**Comment by breznak** [comment]
Thanks David, looks good to me. 
Long time no see. And happy new year and all the best! :fireworks:

**Comment by breznak** [comment]
Btw, seems our CI is not running?

**Review by breznak — APPROVED** [review]
approved, let's see if CI runs..

**Review by ctrl-z-9000-times — APPROVED** [review]
This looks good to me.
I would say to go ahead and merge this even if the CI does not run, BC its clear what went wrong and the fix is very simple.

**Review by breznak — APPROVED** [review]
ok, merging as-is. Fix CI later.

**Pull request merged**
