### PR TITLE
Ported single_layer_2d_experiment from nupic.research

### PR DESCRIPTION
**Pull request by fcr**
Ported single_layer_2d_experiment from nupic.research to htm.core.
This experiment was recently released into the nupic.research public repository and I believe that it could be useful.
This change was built with Xcode 15.4 passed all unit tests on my MacBook Pro running Sonoma 14.5

### CODE REVIEW

**Review by ctrl-z-9000-times — APPROVED** [review]
Hi Fcr,

This experiment looks pretty neat! I'd love to read more about it. Are there any publications written about it yet?

This PR is very large. I haven't actually reviewed most of the code, and so I'm trusting you be sane about merging it in. But IIRC we allow most anything into the "advanced" directory, as a matter of policy, so the size of the code should not be an issue.

Anyways, I will let you merge this as you wish. If you need to amend it or if you want to submit followup PRs, please don't hesitate :)

**Comment by fcr** [comment]
If you want to read more about this see: https://numenta.github.io/htmresearch/documents/location-layer/infer-2d-objects.html

**Comment by fcr** [comment]
I don't think that I am allowed to actually perform the merge.

**Comment by ctrl-z-9000-times** [comment]
I don't think that our CI still works all correctly, and since you already tested it, I'm going to go ahead and merge it without CI.

**Comment by dkeeney** [comment]
Thank you Fred for putting this together.  You already tried it on the MAC so I will try the build on Linux and Windows.  We do not have our automated builds anymore so I will have to do this manually.

I do not see any new regression tests in this set..nothing to automatically prove that these modules run properly.  But since this is experimental and the results are shown in the visualizations perhaps we can skip the automated tests in this case.

How about documentation. Do we have anything to explain how to run these experiments?

**Comment by dkeeney** [comment]
Thanks Dave, Go ahead and do the merge.  I will still do the Linux and Windows builds.

**Comment by fcr** [comment]
I've added a lot of comments to the code as I unravelled it in order to understand it. There is also an explanation in the ReadMe for the visualization  for installing and using it. In addition there is the link I provided above.

**Pull request merged**
